---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=plaidml
install: 
  - "sudo apt update"
  - "sudo apt install -y python3 python3-pip"
  - "sudo -H pip3 install virtualenv"
  - "virtualenv plaidml"
  - "source plaidml/bin/activate"
  - "pip install plaidml"
  - "source ~/.cargo/env || true"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - "echo '$VIRTUAL_ENV'"
  - "cargo build"
  - "cargo test"
sudo: required
